server:
  port: 8888

spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/benjamin-mb/configuration-service.git
          default-label: main
          search-paths: .
          clone-on-start: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info,refresh
    endpoint:
      health:
        show-details: always

  logging:
    level:
      org.springframework.cloud.config: DEBUG
      org.springframework.boot: INFO